In [0]:
import pandas as pd
import numpy as np

In [0]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [0]:
data.replace([-999, -1000.0], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

replace multiple values with multiple values

In [0]:
data.replace([-999.0,-1000.0],[100,200])

0      1.0
1    100.0
2      2.0
3    100.0
4    200.0
5      3.0
dtype: float64

In [0]:
data.replace({-999.0 : 0, -1000.0 : 1})

0    1.0
1    0.0
2    2.0
3    0.0
4    1.0
5    3.0
dtype: float64

##Renaming axis indexes

In [0]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
index=['Ohio', 'Colorado', 'New York'],
columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [0]:
transform = lambda x: x[:4].upper()
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [0]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [0]:
data.rename(index={'Ohio': 'INDIANA'},
columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA     0    1         2     3
Colorado    4    5         6     7
New York    8    9        10    11

##Discretization and Binning

In [0]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [0]:
bins = [18, 25, 35, 60, 100]

In [0]:
#pd.cut (single value, interval)
cats = pd.cut(ages, bins)
cats #ranges
(18,25] index = 1 (25,35] index = 2 (35,60] index = 3 (60,100] index = 4 

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [0]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [0]:
pd.value_counts(cats)    #counts how many values lie in each interval

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [0]:
pd.cut (ages, [18,26,36,61,100], right = False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [0]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [0]:
pd.cut(ages, bins, labels=group_names)   #labels define the names of the intervals 

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [0]:
data = np.random.rand(20)
data

array([0.72240784, 0.48494404, 0.16550928, 0.5090102 , 0.38469662,
       0.05139594, 0.68036832, 0.53987083, 0.44814443, 0.69600982,
       0.29790525, 0.12740829, 0.40585765, 0.5883272 , 0.41038273,
       0.67907563, 0.42277049, 0.52400611, 0.68834332, 0.37070451])

In [0]:
pd.cut(data, 4, precision=2) #4 (divides into 4 equal parts) precision , digits after decimal

[(0.55, 0.72], (0.39, 0.55], (0.051, 0.22], (0.39, 0.55], (0.22, 0.39], ..., (0.55, 0.72], (0.39, 0.55], (0.39, 0.55], (0.55, 0.72], (0.22, 0.39]]
Length: 20
Categories (4, interval[float64]): [(0.051, 0.22] < (0.22, 0.39] < (0.39, 0.55] < (0.55, 0.72]]

In [0]:
data = np.random.randn(1000) # Normally distributed

In [0]:
cats = pd.qcut(data, 4) # Cut into quartiles
cats

[(-0.049, 0.654], (0.654, 3.124], (-0.049, 0.654], (0.654, 3.124], (-0.674, -0.049], ..., (0.654, 3.124], (-3.278, -0.674], (0.654, 3.124], (-3.278, -0.674], (-0.674, -0.049]]
Length: 1000
Categories (4, interval[float64]): [(-3.278, -0.674] < (-0.674, -0.049] < (-0.049, 0.654] <
                                    (0.654, 3.124]]

In [0]:
data = pd.DataFrame(np.random.randn(1000, 4))
data

0         1         2         3
0    1.563592 -0.085372 -0.253365 -1.075770
1   -0.659733 -1.524898  0.238606  0.586574
2    0.710098  0.790761  0.323970 -2.183573
3    0.112109  0.974292 -1.343209 -1.461677
4    0.173475  0.928340 -1.273237 -1.453050
..        ...       ...       ...       ...
995  0.017641 -0.715786  0.229116  0.117290
996 -1.197839 -0.026130 -2.143521  0.755519
997  0.188868  0.121200  0.405258 -1.258589
998 -0.433018 -1.263062  0.678114 -0.677759
999 -1.463601 -0.103004 -0.064669  0.389652

[1000 rows x 4 columns]

In [0]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.030674     0.038776    -0.007061     0.012646
std       0.994784     1.018644     1.006270     1.012786
min      -2.669453    -3.640666    -3.217474    -3.255724
25%      -0.651761    -0.630836    -0.681166    -0.700138
50%       0.023253     0.032842     0.006556     0.036821
75%       0.721211     0.695668     0.671469     0.675482
max       4.023508     3.491859     2.967653     3.874156

In [0]:
col = data.head(10)

In [0]:
col = data[2]
col

0     -0.253365
1      0.238606
2      0.323970
3     -1.343209
4     -1.273237
         ...   
995    0.229116
996   -2.143521
997    0.405258
998    0.678114
999   -0.064669
Name: 2, Length: 1000, dtype: float64

In [0]:
col[np.abs(col) >= 1]

0         1         2         3
0  1.563592       NaN       NaN -1.075770
1       NaN -1.524898       NaN       NaN
2       NaN       NaN       NaN -2.183573
3       NaN       NaN -1.343209 -1.461677
4       NaN       NaN -1.273237 -1.453050
5  1.637648       NaN       NaN       NaN
6       NaN       NaN       NaN       NaN
7       NaN -1.205331       NaN       NaN
8       NaN       NaN       NaN       NaN
9       NaN       NaN -1.006312       NaN

In [0]:
col[np.abs(col) > 3]

0   1   2   3
0 NaN NaN NaN NaN
1 NaN NaN NaN NaN
2 NaN NaN NaN NaN
3 NaN NaN NaN NaN
4 NaN NaN NaN NaN
5 NaN NaN NaN NaN
6 NaN NaN NaN NaN
7 NaN NaN NaN NaN
8 NaN NaN NaN NaN
9 NaN NaN NaN NaN

In [0]:
data[(np.abs(data) > 3).any(1)]    #1 for column

0         1         2         3
24   0.454471  3.095786 -0.137041  0.223400
130 -1.192265  3.117497  1.333377  1.231299
196  3.358836 -0.362226  2.760176  0.887403
332 -0.075373  0.780311 -0.637635  3.325563
338  3.290075  0.982933 -0.165891 -0.148645
454  0.437813 -0.260255 -3.217474  1.070736
510  3.290552  1.340415  0.869115  0.212439
555 -1.088542 -3.640666  1.363399  1.156110
560  0.451260 -1.385922 -3.081497  0.391987
596 -2.249349  3.491859  1.347583  0.291505
639  4.023508  0.599292  1.912893  1.591063
662  1.388011 -0.043532 -0.038077 -3.178769
696 -0.014131 -0.027775 -0.148597  3.874156
827 -0.772319  3.108759 -0.004796 -0.852284
850 -0.037894 -0.575666  0.800063 -3.255724
854 -1.918145  0.764824 -3.055253  0.712719

In [0]:
np.sign(col) #indiates the nature of values, positive or negetive
#1.0 for positive and -1.0 for negetive

0    1    2    3
0  1.0 -1.0 -1.0 -1.0
1 -1.0 -1.0  1.0  1.0
2  1.0  1.0  1.0 -1.0
3  1.0  1.0 -1.0 -1.0
4  1.0  1.0 -1.0 -1.0
5  1.0 -1.0 -1.0  1.0
6  1.0 -1.0  1.0  1.0
7 -1.0 -1.0  1.0  1.0
8  1.0  1.0 -1.0  1.0
9  1.0 -1.0 -1.0  1.0

##Permutation and Random Sampling

In [0]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))

In [0]:
sampler = np.random.permutation(5)
sampler

array([4, 1, 2, 0, 3])

In [0]:
df.take(sampler)

0   1   2   3
4  16  17  18  19
1   4   5   6   7
2   8   9  10  11
0   0   1   2   3
3  12  13  14  15

##Computing Indicator/Dummy Variables

In [0]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
'data1': range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [0]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [0]:
a = [1,2,3]
a.extend([4,5])     #extend adds more than one values
a

[1, 2, 3, 4, 5]

In [0]:
val = 'a,b,cd,effg,h,i,j,kl,mnop'
val = val.split(',')
val

['a', 'b', 'cd', 'effg', 'h', 'i', 'j', 'kl', 'mnop']

In [0]:
val = 'presidential initiative artifical intelligence cloud computing'

In [0]:
val = val.split(' ')
val

['presidential',
 'initiative',
 'artifical',
 'intelligence',
 'cloud',
 'computing']

In [0]:
val[0] + ' ' + val[1] + ' ' + val[2] + ' ' + val[3] + ' ' + val[4] + ' ' + val[5] + ' '

'presidential initiative artifical intelligence cloud computing '

In [0]:
' '.join(val)

'presidential initiative artifical intelligence cloud computing'

In [0]:
'-'.join(val)

'presidential-initiative-artifical-intelligence-cloud-computing'

In [0]:
'presidential' in val

True

In [0]:
val.index('presidential')